### ISSUE TITLE
Cannot resolve module "file:///Users/username/saur"

### ISSUE THREAD

**Issue by gabalicious** [tubbo/saur#2]
I tried installing the cli with `deno install --allow-read=. --allow-write --allow-run saur https://deno.land/x/saur/cli.js` and got this `Cannot resolve module "file:///Users/justingaba/saur"`

I installed deno through homebrew on MacOS 10.15.4

**Comment by tubbo** [comment]
hi there! since Deno v1 released today, a bunch of major breaking changes occurred that we needed to solve for. the CLI syntax for `deno install` has changed to:

    deno install --unstable --allow-read=. --allow-write --allow-run --name saur https://deno.land/x/saur/cli.js

I've updated the docs to reflect this. Thanks!
